<a href="https://colab.research.google.com/github/shivani9133/college/blob/main/movieRecomemdation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [164]:

import numpy as np
import pandas as pd

In [165]:
movies=pd.read_csv('/content/tmdb_5000_movies.csv', on_bad_lines='skip', engine="python")

In [166]:
credits=pd.read_csv('/content/tmdb_5000_credits.csv',on_bad_lines='skip', engine="python")

In [93]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [94]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [95]:
credits.head()['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

In [96]:
movies.merge(credits,on='title').shape

(4809, 23)

In [97]:
movies.shape

(4803, 20)

In [98]:
credits.shape

(4803, 4)

In [99]:
movies=movies.merge(credits,on='title')

In [100]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [101]:
movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
id       2
cs       2
ta       2
ro       2
ar       2
te       1
hu       1
xx       1
af       1
is       1
tr       1
vi       1
pl       1
nb       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

In [102]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [103]:
#genres
#id
#keywords
#title
#overview
#cast
#crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [104]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [105]:
movies.isnull()

      movie_id  title  overview  genres  keywords   cast   crew
0        False  False     False   False     False  False  False
1        False  False     False   False     False  False  False
2        False  False     False   False     False  False  False
3        False  False     False   False     False  False  False
4        False  False     False   False     False  False  False
...        ...    ...       ...     ...       ...    ...    ...
4804     False  False     False   False     False  False  False
4805     False  False     False   False     False  False  False
4806     False  False     False   False     False  False  False
4807     False  False     False   False     False  False  False
4808     False  False     False   False     False  False  False

[4809 rows x 7 columns]

In [106]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [107]:
movies.dropna(inplace=True)

In [108]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [109]:
movies.duplicated().sum()

np.int64(0)

In [110]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [111]:
def convert(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [112]:
import ast
movies['genres']=movies['genres'].apply(convert)

In [113]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [114]:
movies['keywords']=movies['keywords'].apply(convert)

In [115]:
movies['keywords']

0       [culture clash, future, space war, space colon...
1       [ocean, drug abuse, exotic island, east india ...
2       [spy, based on novel, secret agent, sequel, mi...
3       [dc comics, crime fighter, terrorist, secret i...
4       [based on novel, mars, medallion, space travel...
                              ...
4804    [united states–mexico barrier, legs, arms, pap...
4805                                                   []
4806    [date, love at first sight, narration, investi...
4807                                                   []
4808            [obsession, camcorder, crush, dream girl]
Name: keywords, Length: 4806, dtype: object

In [116]:
movies['cast'][0]

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu\'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na\'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav\'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch\'s Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na\'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]'

In [117]:
def convert3(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
      L.append(i['name'])
      counter+=1
    else:
      break
  return L

In [118]:
movies['cast']=movies['cast'].apply(convert3)

In [119]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [120]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [134]:
def fetch_director(text):
  L=[]
  for i in ast.literal_eval(text):
    if i['job']=='Director':
      L.append(i['name'])
      break
  return L

In [157]:
movies['crew'].apply(fetch_director)

ValueError: malformed node or string: ['[', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '2', '3', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'E', 'd', 'i', 't', 'i', 'n', 'g', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '1', '7', '2', '1', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'E', 'd', 'i', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'S', 't', 'e', 'p', 'h', 'e', 'n', '', 'E', '.', '', 'R', 'i', 'v', 'k', 'i', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '3', '9', 'c', '4', '7', 'e', 'c', 'c', '3', 'a', '3', '6', '8', '1', '0', 'e', '3', '0', '0', '1', 'f', '8', '7', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '4', '9', '6', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '', 'D', 'e', 's', 'i', 'g', 'n', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'R', 'i', 'c', 'k', '', 'C', 'a', 'r', 't', 'e', 'r', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '4', '9', '1', 'c', '8', '9', 'c', '3', 'a', '3', '6', '8', '0', 'f', 'b', '4', '0', '0', '1', 'c', 'f', '7', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '9', '0', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '', 'D', 'e', 's', 'i', 'g', 'n', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'C', 'h', 'r', 'i', 's', 't', 'o', 'p', 'h', 'e', 'r', '', 'B', 'o', 'y', 'e', 's', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '4', '9', '1', 'c', 'b', '7', '0', 'e', '0', 'a', '2', '6', '7', '4', '8', '0', '0', '0', '1', 'b', 'd', '0', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '9', '0', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'u', 'p', 'e', 'r', 'v', 'i', 's', 'i', 'n', 'g', '', 'S', 'o', 'u', 'n', 'd', '', 'E', 'd', 'i', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'C', 'h', 'r', 'i', 's', 't', 'o', 'p', 'h', 'e', 'r', '', 'B', 'o', 'y', 'e', 's', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '3', '9', 'c', '4', 'a', '4', 'c', 'c', '3', 'a', '3', '6', '8', '1', '0', 'c', '9', '0', '0', '2', '1', '0', '1', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '1', ',', '', '"', 'i', 'd', '"', ':', '', '1', '2', '6', '2', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'C', 'a', 's', 't', 'i', 'n', 'g', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'M', 'a', 'l', 'i', '', 'F', 'i', 'n', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '5', '4', '4', 'e', 'e', '3', 'b', '9', '2', '5', '1', '4', '1', '4', '9', '9', 'f', '0', '0', '0', '8', 'f', 'c', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '1', '7', '2', '9', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'O', 'r', 'i', 'g', 'i', 'n', 'a', 'l', '', 'M', 'u', 's', 'i', 'c', '', 'C', 'o', 'm', 'p', 'o', 's', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'a', 'm', 'e', 's', '', 'H', 'o', 'r', 'n', 'e', 'r', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', '9', 'c', '3', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'D', 'i', 'r', 'e', 'c', 't', 'i', 'n', 'g', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '2', '7', '1', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'a', 'm', 'e', 's', '', 'C', 'a', 'm', 'e', 'r', 'o', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', '9', 'd', '9', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'W', 'r', 'i', 't', 'i', 'n', 'g', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '2', '7', '1', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'W', 'r', 'i', 't', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'a', 'm', 'e', 's', '', 'C', 'a', 'm', 'e', 'r', 'o', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '1', '7', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'E', 'd', 'i', 't', 'i', 'n', 'g', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '2', '7', '1', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'E', 'd', 'i', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'a', 'm', 'e', 's', '', 'C', 'a', 'm', 'e', 'r', 'o', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '2', '9', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '2', '7', '1', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'a', 'm', 'e', 's', '', 'C', 'a', 'm', 'e', 'r', 'o', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '3', 'f', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'W', 'r', 'i', 't', 'i', 'n', 'g', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '2', '7', '1', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'c', 'r', 'e', 'e', 'n', 'p', 'l', 'a', 'y', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'a', 'm', 'e', 's', '', 'C', 'a', 'm', 'e', 'r', 'o', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '3', '9', 'c', '4', '9', '8', '7', 'c', '3', 'a', '3', '6', '8', '1', '0', 'b', 'a', '0', '0', '2', '1', 'a', '4', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '7', '2', '3', '6', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'A', 'r', 't', '', 'D', 'i', 'r', 'e', 'c', 't', 'i', 'o', 'n', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'A', 'n', 'd', 'r', 'e', 'w', '', 'M', 'e', 'n', 'z', 'i', 'e', 's', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '9', '5', '9', '8', 'c', '3', 'c', '3', 'a', '3', '6', '8', '6', 'a', 'e', '9', '0', '0', '4', '3', '8', '3', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'V', 'i', 's', 'u', 'a', 'l', '', 'E', 'f', 'f', 'e', 'c', 't', 's', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '6', '6', '9', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'V', 'i', 's', 'u', 'a', 'l', '', 'E', 'f', 'f', 'e', 'c', 't', 's', '', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'i', 'l', 'l', '', 'B', 'r', 'o', 'o', 'k', 's', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '4', 'b', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '1', ',', '', '"', 'i', 'd', '"', ':', '', '6', '3', '4', '7', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'C', 'a', 's', 't', 'i', 'n', 'g', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'M', 'a', 'r', 'g', 'e', 'r', 'y', '', 'S', 'i', 'm', 'k', 'i', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '7', '0', 'b', '6', 'f', '4', '1', '9', '2', '5', '1', '4', '1', '7', 'd', 'a', '7', '0', '0', '3', '2', 'f', 'e', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '6', '8', '7', '8', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'u', 'p', 'e', 'r', 'v', 'i', 's', 'i', 'n', 'g', '', 'A', 'r', 't', '', 'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'K', 'e', 'v', 'i', 'n', '', 'I', 's', 'h', 'i', 'o', 'k', 'a', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '9', '5', 'a', '0', 'f', 'a', 'c', '3', 'a', '3', '6', '8', '6', 'a', 'e', '9', '0', '0', '4', '4', '6', '8', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '6', '8', '8', '3', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'M', 'u', 's', 'i', 'c', '', 'E', 'd', 'i', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'D', 'i', 'c', 'k', '', 'B', 'e', 'r', 'n', 's', 't', 'e', 'i', 'n', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '9', '5', '9', '7', '0', '6', 'c', '3', 'a', '3', '6', '8', '6', 'a', 'f', '3', '0', '0', '3', 'e', '8', '1', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '8', '1', '5', '9', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '', 'E', 'f', 'f', 'e', 'c', 't', 's', '', 'E', 'd', 'i', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'S', 'h', 'a', 'n', 'n', 'o', 'n', '', 'M', 'i', 'l', 'l', 's', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '4', '9', '1', 'd', '5', '8', 'c', '3', 'a', '3', '6', '8', '0', 'f', 'b', '1', '0', '0', '1', 'c', 'c', 'b', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '8', '1', '6', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'F', 'o', 'l', 'e', 'y', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'D', 'e', 'n', 'n', 'i', 'e', '', 'T', 'h', 'o', 'r', 'p', 'e', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '4', '9', '1', 'd', '6', 'c', 'c', '3', 'a', '3', '6', '8', '0', 'f', 'a', '5', '0', '0', '1', 'b', '2', 'c', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'S', 'o', 'u', 'n', 'd', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '8', '1', '6', '3', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'F', 'o', 'l', 'e', 'y', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'a', 'n', 'a', '', 'V', 'a', 'n', 'c', 'e', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '5', '7', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'C', 'o', 's', 't', 'u', 'm', 'e', '', '&', '', 'M', 'a', 'k', 'e', '-', 'U', 'p', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '1', ',', '', '"', 'i', 'd', '"', ':', '', '8', '5', '2', '7', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'C', 'o', 's', 't', 'u', 'm', 'e', '', 'D', 'e', 's', 'i', 'g', 'n', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'D', 'e', 'b', 'o', 'r', 'a', 'h', '', 'L', 'y', 'n', 'n', '', 'S', 'c', 'o', 't', 't', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '2', 'f', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '8', '5', '2', '9', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'J', 'o', 'n', '', 'L', 'a', 'n', 'd', 'a', 'u', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '3', '9', 'c', '4', '9', '3', '7', 'c', '3', 'a', '3', '6', '8', '1', '0', 'b', 'a', '0', '0', '2', '1', '9', '4', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '9', '6', '1', '8', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'A', 'r', 't', '', 'D', 'i', 'r', 'e', 'c', 't', 'i', 'o', 'n', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'S', 'e', 'a', 'n', '', 'H', 'a', 'w', 'o', 'r', 't', 'h', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '3', '9', 'c', '4', '9', 'b', '6', 'c', '3', 'a', '3', '6', '8', '1', '0', 'c', '1', '0', '0', '2', '0', 'e', '6', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '1', ',', '', '"', 'i', 'd', '"', ':', '', '1', '2', '6', '5', '3', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'e', 't', '', 'D', 'e', 'c', 'o', 'r', 'a', 't', 'i', 'o', 'n', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'K', 'i', 'm', '', 'S', 'i', 'n', 'c', 'l', 'a', 'i', 'r', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '7', '0', 'b', '6', 'f', '2', 'f', '9', '2', '5', '1', '4', '1', '3', 'a', '0', 'e', '0', '0', '0', '2', '0', 'd', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '1', ',', '', '"', 'i', 'd', '"', ':', '', '1', '2', '6', '5', '3', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'u', 'p', 'e', 'r', 'v', 'i', 's', 'i', 'n', 'g', '', 'A', 'r', 't', '', 'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'K', 'i', 'm', '', 'S', 'i', 'n', 'c', 'l', 'a', 'i', 'r', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '4', '9', '1', 'a', '6', 'c', '0', 'e', '0', 'a', '2', '6', '7', '4', '8', 'c', '0', '0', '1', 'b', '1', '9', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '1', '4', '3', '5', '0', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'S', 'e', 't', '', 'D', 'e', 's', 'i', 'g', 'n', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'R', 'i', 'c', 'h', 'a', 'r', 'd', '', 'F', '.', '', 'M', 'a', 'y', 's', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '6', '9', '2', '8', 'c', 'f', '4', 'c', '3', 'a', '3', '6', '8', '4', 'c', 'f', 'f', '0', '0', '2', '5', 'c', '4', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'P', 'r', 'o', 'd', 'u', 'c', 't', 'i', 'o', 'n', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '1', ',', '', '"', 'i', 'd', '"', ':', '', '2', '0', '2', '9', '4', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'E', 'x', 'e', 'c', 'u', 't', 'i', 'v', 'e', '', 'P', 'r', 'o', 'd', 'u', 'c', 'e', 'r', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'L', 'a', 'e', 't', 'a', '', 'K', 'a', 'l', 'o', 'g', 'r', 'i', 'd', 'i', 's', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '5', '1', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'C', 'o', 's', 't', 'u', 'm', 'e', '', '&', '', 'M', 'a', 'k', 'e', '-', 'U', 'p', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '0', ',', '', '"', 'i', 'd', '"', ':', '', '1', '7', '6', '7', '5', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'C', 'o', 's', 't', 'u', 'm', 'e', '', 'D', 'e', 's', 'i', 'g', 'n', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'M', 'a', 'y', 'e', 's', '', 'C', '.', '', 'R', 'u', 'b', 'e', 'o', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '2', 'f', 'e', '4', '8', '0', '0', '9', '2', '5', '1', '4', '1', '6', 'c', '7', '5', '0', 'a', 'c', 'a', '1', '1', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'C', 'a', 'm', 'e', 'r', 'a', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':', '', '2', ',', '', '"', 'i', 'd', '"', ':', '', '1', '8', '2', '6', '5', ',', '', '"', 'j', 'o', 'b', '"', ':', '', '"', 'D', 'i', 'r', 'e', 'c', 't', 'o', 'r', '', 'o', 'f', '', 'P', 'h', 'o', 't', 'o', 'g', 'r', 'a', 'p', 'h', 'y', '"', ',', '', '"', 'n', 'a', 'm', 'e', '"', ':', '', '"', 'M', 'a', 'u', 'r', 'o', '', 'F', 'i', 'o', 'r', 'e', '"', '}', ',', '', '{', '"', 'c', 'r', 'e', 'd', 'i', 't', '_', 'i', 'd', '"', ':', '', '"', '5', '4', '4', '9', '1', '9', '4', 'd', '0', 'e', '0', 'a', '2', '6', '7', '4', '8', 'f', '0', '0', '1', 'b', '3', '9', '"', ',', '', '"', 'd', 'e', 'p', 'a', 'r', 't', 'm', 'e', 'n', 't', '"', ':', '', '"', 'A', 'r', 't', '"', ',', '', '"', 'g', 'e', 'n', 'd', 'e', 'r', '"', ':

In [123]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [124]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [125]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [126]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [159]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])

In [160]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."

In [152]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [154]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."

In [163]:
new_df=movies[['movie_id','title','tags']]

KeyError: "['tags'] not in index"

In [140]:

new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [141]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"i n t h e 2 2 n d c e n t u r y , a ..."
1,285,Pirates of the Caribbean: At World's End,"c a p t a i n b a r b o s s a , l o n g ..."
2,206647,Spectre,a c r y p t i c m e s s a g f r o m b ...
3,49026,The Dark Knight Rises,f o l l o w t h e d e a t h o f d i s ...
4,49529,John Carter,j o h n c a r t e r i s a w a r - w e ...

In [142]:
import nltk

In [143]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

In [144]:
new_df['tags']=new_df['tags'].apply(stem)

In [145]:
new_df['tags'][0]

'i n t h e 2 2 n d c e n t u r y , a p a r a p l e g m a r i n i s d i s p a t c h t o t h e m o o n p a n d o r a o n a u n i q u m i s s i o n , b u t b e c o m t o r n b e t w e e n f o l l o w o r d e r a n d p r o t e c t a n a l i e n c i v i l i z a t i o n . a c t i o n a d v e n t u r f a n t a s i s c i e n c e f i c t c u l t u r e c l a s h f u t u r s p a c e w a r s p a c e c o l o n i s o c i e t i s p a c e t r a v e l f u t u r i s t r o m a n c s p a c e a l i e n t r i b e a l i e n p l a n e t c g i m a r i n s o l d i e r b a t t l l o v e a f f a i r a n t i w a r p o w e r r e l m i n d a n d s o u l 3 d s a m w o r t h i n g t o n z o e s a l d a n a s i g o u r n e y w e a v [ { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 3 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 7 2 1 , " j o b " : " e d i t o r " , " n a m e " : " s t e p h e n e . r i v k i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 7 e c c 3 a 3 6 8 1 0 e 3 0 0 1 f 8 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 4 9 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r i c k c a r t e r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c 8 9 c 3 a 3 6 8 0 f b 4 0 0 1 c f 7 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s o u n d d e s i g n e r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b d 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s u p e r v i s i n g s o u n d e d i t o r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 4 c c 3 a 3 6 8 1 0 c 9 0 0 2 1 0 1 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 1 2 6 2 , " j o b " : " c a s t i n g " , " n a m e " : " m a l i f i n n " } , { " c r e d i t _ i d " : " 5 5 4 4 e e 3 b 9 2 5 1 4 1 4 9 9 f 0 0 0 8 f c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 2 , " i d " : 1 7 2 9 , " j o b " : " o r i g i n a l m u s i c c o m p o s e r " , " n a m e " : " j a m e s h o r n e r " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c 3 " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " d i r e c t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 9 " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " w r i t e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 7 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " e d i t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 9 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " p r o d u c e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 f " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " s c r e e n p l a y " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 8 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 a 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 7 2 3 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d r e w m e n z i e s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 8 c 3 c 3 a 3 6 8 6 a e 9 0 0 4 3 8 3 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 6 6 9 0 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " j i l l b r o o k s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 b " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 6 3 4 7 , " j o b " : " c a s t i n g " , " n a m e " : " m a r g e r y s i m k i n " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 4 1 9 2 5 1 4 1 7 d a 7 0 0 3 2 f e " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 6 8 7 8 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k e v i n i s h i o k a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 0 f a c 3 a 3 6 8 6 a e 9 0 0 4 4 6 8 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 6 8 8 3 , " j o b " : " m u s i c e d i t o r " , " n a m e " : " d i c k b e r n s t e i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 0 6 c 3 a 3 6 8 6 a f 3 0 0 3 e 8 1 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 5 9 , " j o b " : " s o u n d e f f e c t s e d i t o r " , " n a m e " : " s h a n n o n m i l l s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 5 8 c 3 a 3 6 8 0 f b 1 0 0 1 c c b " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 0 , " j o b " : " f o l e y " , " n a m e " : " d e n n i e t h o r p e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 6 c c 3 a 3 6 8 0 f a 5 0 0 1 b 2 c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 3 , " j o b " : " f o l e y " , " n a m e " : " j a n a v a n c e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 7 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 8 5 2 7 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " d e b o r a h l y n n s c o t t " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 f " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 8 5 2 9 , " j o b " : " p r o d u c e r " , " n a m e " : " j o n l a n d a u " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 3 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 6 1 8 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s e a n h a w o r t h " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 b 6 c 3 a 3 6 8 1 0 c 1 0 0 2 0 e 6 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s e t d e c o r a t i o n " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 2 f 9 2 5 1 4 1 3 a 0 e 0 0 0 2 0 d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 6 c 0 e 0 a 2 6 7 4 8 c 0 0 1 b 1 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 4 3 5 0 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " r i c h a r d f . m a y s " } , { " c r e d i t _ i d " : " 5 6 9 2 8 c f 4 c 3 a 3 6 8 4 c f f 0 0 2 5 c 4 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 2 0 2 9 4 , " j o b " : " e x e c u t i v e p r o d u c e r " , " n a m e " : " l a e t a k a l o g r i d i s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 1 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 7 6 7 5 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " m a y e s c . r u b e o " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 1 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 1 8 2 6 5 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " m a u r o f i o r e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 4 d 0 e 0 a 2 6 7 4 8 f 0 0 1 b 3 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 4 2 2 8 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s c o t t h e r b e r t s o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 0 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " j o b " : " s t u n t s " , " n a m e " : " w o o d y s c h u l t z " } , { " c r e d i t _ i d " : " 5 5 9 2 a e f b 9 2 5 1 4 1 5 2 d e 0 0 1 0 f 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 5 9 2 a f a 4 9 2 5 1 4 1 5 2 d e 0 0 1 1 2 c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " h a i r s t y l i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e d 5 9 2 5 1 4 1 3 0 f c 0 0 2 e 5 d " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 3 3 3 0 2 , " j o b " : " c a m e r a o p e r a t o r " , " n a m e " : " r i c h a r d b l u c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 9 1 c 3 a 3 6 8 1 0 b a 0 0 2 1 4 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 3 3 3 0 3 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s i m o n b r i g h t " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 0 6 9 2 5 1 4 1 7 a 8 1 0 0 1 f 3 a " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 1 3 1 4 5 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " r i c h a r d m a r t i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 a 0 d c 3 a 3 6 8 0 f f 5 0 0 2 c 8 d " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 5 8 1 8 8 , " j o b " : " v i s u a l e f f e c t s e d i t o r " , " n a m e " : " s t e v e r . m o o r e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 d " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 5 8 8 7 1 , " j o b " : " e d i t o r " , " n a m e " : " j o h n r e f o u a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 4 d c 3 a 3 6 8 0 f c 3 0 0 1 8 c a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 2 3 5 9 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " k a r l j . m a r t i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 5 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 1 , " i d " : 7 2 2 0 1 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " c h i l i n g l i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f f " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " j o b " : " s t u n t s " , " n a m e " : " i l r a m c h o i " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 5 2 9 2 5 1 4 1 6 e 2 b 0 0 4 3 9 4 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 3 2 1 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e v e n q u a l e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 e d f 0 e 0 a 2 6 7 4 8 9 0 0 1 c 3 7 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 1 , " i d " : 1 2 2 6 0 7 , " j o b " : " d i a l e c t c o a c h " , " n a m e " : " c a r l a m e y e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 5 b c 3 a 3 6 8 6 5 3 d 0 0 1 a 3 a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 3 2 5 8 5 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " n i c k b a s s e t t " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 0 3 c 3 a 3 6 8 6 5 3 d 0 0 1 a 7 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 5 9 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " j i l l c o r m a c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 6 7 c 3 a 3 6 8 6 5 3 d 0 0 1 a 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 6 0 4 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d y m c l a r e n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " j o b " : " m o t i o n c a p t u r e a r t i s t " , " n a m e " : " t e r r y n o t a r y " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 0 2 c 3 a 3 6 8 0 f c 6 0 0 2 7 d 2 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 9 5 6 1 9 8 , " j o b " : " s t u n t c o o r d i n a t o r " , " n a m e " : " g a r r e t t w a r r e n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c a 3 c 3 a 3 6 8 6 a e 3 0 0 4 3 8 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 5 7 8 7 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n r o t h b a r t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 5 1 9 2 5 1 4 1 2 c 7 4 0 0 1 b 2 f " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 5 7 8 8 9 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " s t e f a n d e c h a n t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 6 2 c 3 a 3 6 8 0 b 7 7 0 0 7 4 6 0 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 9 5 9 5 5 5 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " t o d d c h e r n i a w s k y " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 3 a c 3 a 3 6 8 1 0 d a 0 0 2 1 c c " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 0 , " i d " : 1 0 1 6 1 7 7 , " j o b " : " c a s t i n g " , " n a m e " : " m i r a n d a r i v e r s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 2 c c 3 a 3 6 8 1 0 c 1 0 0 2 0 6 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 0 3 2 5 3 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r o b e r t s t r o m b e r g " } , { " c r e d i t _ i d " : " 5 3 9 c 4 b 6 5 c 3 a 3 6 8 1 0 c 9 0 0 2 1 2 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 0 7 1 6 8 0 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " j o h n h a r d i n g " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 6 6 9 2 5 1 4 1 3 0 f c 0 0 2 e 4 e " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 0 , " i d " : 1 1 7 7 3 6 4 , " j o b " : " s t e a d i c a m o p e r a t o r " , " n a m e " : " r o b e r t o d e a n g e l i s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 f 1 c 3 a 3 6 8 6 5 3 d 0 0 1 a a c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 2 0 2 8 5 0 , " j o b " : " m a k e u p d e p a r t m e n t h e a d " , " n a m e " : " m i k e s m i t h s o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 9 9 e c 3 a 3 6 8 6 a e 1 0 0 4 6 0 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 4 6 6 8 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " a l a i n l a l a n n e " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c d f c 3 a 3 6 8 1 1 5 3 0 0 2 7 2 9 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 6 4 1 0 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " l u c a s s a l t o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 6 2 3 9 2 5 1 4 1 7 a 8 1 0 0 1 e a e " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 2 3 4 2 6 6 , " j o b " : " p o s t p r o d u c t i o n s u p e r v i s o r " , " n a m e " : " j a n a c e t a s h j i a n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 8 5 9 2 5 1 4 1 6 e 1 e 0 0 3 e f e " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 7 1 9 3 2 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e p h e n r o s e n b a u m " } , { " c r e d i t _ i d " : " 5 5 9 2 a f 2 8 c 3 a 3 6 8 7 7 5 a 0 0 1 0 5 f " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 1 0 0 6 4 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " f r a n k i e k a r e n a " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a d f c 3 a 3 6 8 1 0 e 3 0 0 2 0 3 b " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 1 3 1 9 8 4 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " l i s a l o v a a s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 b 5 7 9 2 5 1 4 1 6 e 2 b 0 0 4 3 7 1 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 3 2 7 0 2 8 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n f a w k n e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 a 7 c 3 a 3 6 8 1 0 b 5 0 0 1 f a 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 1 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " r o b e r t b a v i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 7 1 c 3 a 3 6 8 1 0 d a 0 0 2 1 e 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 7 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " a n t h o n y a l m a r a z " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 8 a c 3 a 3 6 8 1 0 b a 0 0 2 1 e 4 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 0 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " c a r o l y n m . f e n t o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a b 6 c 3 a 3 6 8 1 0 d a 0 0 2 1 f 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " b e t h k o e n i g s b e r g " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b a 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 6 1 9 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s a m p a g e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 d 9 c 3 a 3 6 8 0 f c 3 0 0 1 8 b d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 9 4 4 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t e x k a d o n a g a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c f 5 0 e 0 a 2 6 7 4 8 3 0 0 1 b 0 c " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 3 5 2 4 2 2 , " j o b " : " d i a l o g u e e d i t o r " , " n a m e " : " k i m f o s c a t o " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 f 4 0 e 0 a 2 6 7 4 8 c 0 0 1 b 0 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 5 2 9 6 2 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t a m m y s . l e e " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 1 5 c 3 a 3 6 8 0 f f 5 0 0 2 d 7 1 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 0 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " d e n n y c a i r a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 2 f 9 2 5 1 4 1 3 0 f c 0 0 2 e 9 4 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 1 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " j a m e s w a i t k u s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 6 f c 3 a 3 6 8 1 1 5 3 0 0 2 6 b 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 1 3 6 0 1 0 3 , " j o b " : " s u p e r

In [146]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [147]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"i n t h e 2 2 n d c e n t u r y , a p a r a p ..."
1,285,Pirates of the Caribbean: At World's End,"c a p t a i n b a r b o s s a , l o n g b e l ..."
2,206647,Spectre,a c r y p t i c m e s s a g f r o m b o n d ’ ...
3,49026,The Dark Knight Rises,f o l l o w t h e d e a t h o f d i s t r i c ...
4,49529,John Carter,"j o h n c a r t e r i s a w a r - w e a r y , ..."

In [148]:
new_df['tags'][0]

'i n t h e 2 2 n d c e n t u r y , a p a r a p l e g m a r i n i s d i s p a t c h t o t h e m o o n p a n d o r a o n a u n i q u m i s s i o n , b u t b e c o m t o r n b e t w e e n f o l l o w o r d e r a n d p r o t e c t a n a l i e n c i v i l i z a t i o n . a c t i o n a d v e n t u r f a n t a s i s c i e n c e f i c t c u l t u r e c l a s h f u t u r s p a c e w a r s p a c e c o l o n i s o c i e t i s p a c e t r a v e l f u t u r i s t r o m a n c s p a c e a l i e n t r i b e a l i e n p l a n e t c g i m a r i n s o l d i e r b a t t l l o v e a f f a i r a n t i w a r p o w e r r e l m i n d a n d s o u l 3 d s a m w o r t h i n g t o n z o e s a l d a n a s i g o u r n e y w e a v [ { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 3 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 7 2 1 , " j o b " : " e d i t o r " , " n a m e " : " s t e p h e n e . r i v k i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 7 e c c 3 a 3 6 8 1 0 e 3 0 0 1 f 8 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 4 9 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r i c k c a r t e r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c 8 9 c 3 a 3 6 8 0 f b 4 0 0 1 c f 7 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s o u n d d e s i g n e r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b d 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 9 0 0 , " j o b " : " s u p e r v i s i n g s o u n d e d i t o r " , " n a m e " : " c h r i s t o p h e r b o y e s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 4 c c 3 a 3 6 8 1 0 c 9 0 0 2 1 0 1 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 1 2 6 2 , " j o b " : " c a s t i n g " , " n a m e " : " m a l i f i n n " } , { " c r e d i t _ i d " : " 5 5 4 4 e e 3 b 9 2 5 1 4 1 4 9 9 f 0 0 0 8 f c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 2 , " i d " : 1 7 2 9 , " j o b " : " o r i g i n a l m u s i c c o m p o s e r " , " n a m e " : " j a m e s h o r n e r " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 c 3 " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " d i r e c t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 d 9 " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " w r i t e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 7 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " e d i t o r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 9 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " p r o d u c e r " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 f " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 2 7 1 0 , " j o b " : " s c r e e n p l a y " , " n a m e " : " j a m e s c a m e r o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 8 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 a 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 7 2 3 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d r e w m e n z i e s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 8 c 3 c 3 a 3 6 8 6 a e 9 0 0 4 3 8 3 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 6 6 9 0 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " j i l l b r o o k s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 b " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 6 3 4 7 , " j o b " : " c a s t i n g " , " n a m e " : " m a r g e r y s i m k i n " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 4 1 9 2 5 1 4 1 7 d a 7 0 0 3 2 f e " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 6 8 7 8 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k e v i n i s h i o k a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 0 f a c 3 a 3 6 8 6 a e 9 0 0 4 4 6 8 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 6 8 8 3 , " j o b " : " m u s i c e d i t o r " , " n a m e " : " d i c k b e r n s t e i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 0 6 c 3 a 3 6 8 6 a f 3 0 0 3 e 8 1 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 5 9 , " j o b " : " s o u n d e f f e c t s e d i t o r " , " n a m e " : " s h a n n o n m i l l s " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 5 8 c 3 a 3 6 8 0 f b 1 0 0 1 c c b " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 0 , " j o b " : " f o l e y " , " n a m e " : " d e n n i e t h o r p e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 d 6 c c 3 a 3 6 8 0 f a 5 0 0 1 b 2 c " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 8 1 6 3 , " j o b " : " f o l e y " , " n a m e " : " j a n a v a n c e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 7 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 8 5 2 7 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " d e b o r a h l y n n s c o t t " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 2 f " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 8 5 2 9 , " j o b " : " p r o d u c e r " , " n a m e " : " j o n l a n d a u " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 3 7 c 3 a 3 6 8 1 0 b a 0 0 2 1 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 6 1 8 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s e a n h a w o r t h " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 b 6 c 3 a 3 6 8 1 0 c 1 0 0 2 0 e 6 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s e t d e c o r a t i o n " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 2 f 9 2 5 1 4 1 3 a 0 e 0 0 0 2 0 d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 1 2 6 5 3 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " k i m s i n c l a i r " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 6 c 0 e 0 a 2 6 7 4 8 c 0 0 1 b 1 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 4 3 5 0 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " r i c h a r d f . m a y s " } , { " c r e d i t _ i d " : " 5 6 9 2 8 c f 4 c 3 a 3 6 8 4 c f f 0 0 2 5 c 4 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 2 0 2 9 4 , " j o b " : " e x e c u t i v e p r o d u c e r " , " n a m e " : " l a e t a k a l o g r i d i s " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 5 1 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 7 6 7 5 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " m a y e s c . r u b e o " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 1 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 1 8 2 6 5 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " m a u r o f i o r e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 4 d 0 e 0 a 2 6 7 4 8 f 0 0 1 b 3 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 4 2 2 8 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s c o t t h e r b e r t s o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 0 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 4 2 2 8 8 , " j o b " : " s t u n t s " , " n a m e " : " w o o d y s c h u l t z " } , { " c r e d i t _ i d " : " 5 5 9 2 a e f b 9 2 5 1 4 1 5 2 d e 0 0 1 0 f 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 5 9 2 a f a 4 9 2 5 1 4 1 5 2 d e 0 0 1 1 2 c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 2 9 0 6 7 , " j o b " : " h a i r s t y l i s t " , " n a m e " : " l i n d a d e v e t t a " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e d 5 9 2 5 1 4 1 3 0 f c 0 0 2 e 5 d " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 3 3 3 0 2 , " j o b " : " c a m e r a o p e r a t o r " , " n a m e " : " r i c h a r d b l u c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 9 1 c 3 a 3 6 8 1 0 b a 0 0 2 1 4 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 3 3 3 0 3 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " s i m o n b r i g h t " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 0 6 9 2 5 1 4 1 7 a 8 1 0 0 1 f 3 a " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 1 3 1 4 5 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " r i c h a r d m a r t i n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 a 0 d c 3 a 3 6 8 0 f f 5 0 0 2 c 8 d " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 5 8 1 8 8 , " j o b " : " v i s u a l e f f e c t s e d i t o r " , " n a m e " : " s t e v e r . m o o r e " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 1 d " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 5 8 8 7 1 , " j o b " : " e d i t o r " , " n a m e " : " j o h n r e f o u a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a 4 d c 3 a 3 6 8 0 f c 3 0 0 1 8 c a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 2 3 5 9 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " k a r l j . m a r t i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 3 5 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 1 , " i d " : 7 2 2 0 1 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " c h i l i n g l i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c 9 f f " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 8 9 7 1 4 , " j o b " : " s t u n t s " , " n a m e " : " i l r a m c h o i " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 5 2 9 2 5 1 4 1 6 e 2 b 0 0 4 3 9 4 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 3 2 1 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e v e n q u a l e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 e d f 0 e 0 a 2 6 7 4 8 9 0 0 1 c 3 7 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 1 , " i d " : 1 2 2 6 0 7 , " j o b " : " d i a l e c t c o a c h " , " n a m e " : " c a r l a m e y e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 5 b c 3 a 3 6 8 6 5 3 d 0 0 1 a 3 a " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 3 2 5 8 5 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " n i c k b a s s e t t " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 0 3 c 3 a 3 6 8 6 5 3 d 0 0 1 a 7 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 5 9 6 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " j i l l c o r m a c k " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 6 7 c 3 a 3 6 8 6 5 3 d 0 0 1 a 9 4 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 2 6 0 4 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " a n d y m c l a r e n " } , { " c r e d i t _ i d " : " 5 2 f e 4 8 0 0 9 2 5 1 4 1 6 c 7 5 0 a c a 4 5 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 2 3 6 6 9 6 , " j o b " : " m o t i o n c a p t u r e a r t i s t " , " n a m e " : " t e r r y n o t a r y " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 0 2 c 3 a 3 6 8 0 f c 6 0 0 2 7 d 2 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 9 5 6 1 9 8 , " j o b " : " s t u n t c o o r d i n a t o r " , " n a m e " : " g a r r e t t w a r r e n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c a 3 c 3 a 3 6 8 6 a e 3 0 0 4 3 8 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 2 , " i d " : 9 5 7 8 7 4 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n r o t h b a r t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 5 1 9 2 5 1 4 1 2 c 7 4 0 0 1 b 2 f " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 9 5 7 8 8 9 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " s t e f a n d e c h a n t " } , { " c r e d i t _ i d " : " 5 7 0 b 6 f 6 2 c 3 a 3 6 8 0 b 7 7 0 0 7 4 6 0 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 9 5 9 5 5 5 , " j o b " : " s u p e r v i s i n g a r t d i r e c t o r " , " n a m e " : " t o d d c h e r n i a w s k y " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 3 a c 3 a 3 6 8 1 0 d a 0 0 2 1 c c " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 0 , " i d " : 1 0 1 6 1 7 7 , " j o b " : " c a s t i n g " , " n a m e " : " m i r a n d a r i v e r s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 2 c c 3 a 3 6 8 1 0 c 1 0 0 2 0 6 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 0 3 2 5 3 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r o b e r t s t r o m b e r g " } , { " c r e d i t _ i d " : " 5 3 9 c 4 b 6 5 c 3 a 3 6 8 1 0 c 9 0 0 2 1 2 5 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 0 7 1 6 8 0 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " j o h n h a r d i n g " } , { " c r e d i t _ i d " : " 5 4 9 5 9 e 6 6 9 2 5 1 4 1 3 0 f c 0 0 2 e 4 e " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 0 , " i d " : 1 1 7 7 3 6 4 , " j o b " : " s t e a d i c a m o p e r a t o r " , " n a m e " : " r o b e r t o d e a n g e l i s " } , { " c r e d i t _ i d " : " 5 3 9 c 4 9 f 1 c 3 a 3 6 8 6 5 3 d 0 0 1 a a c " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 2 , " i d " : 1 2 0 2 8 5 0 , " j o b " : " m a k e u p d e p a r t m e n t h e a d " , " n a m e " : " m i k e s m i t h s o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 9 9 e c 3 a 3 6 8 6 a e 1 0 0 4 6 0 c " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 4 6 6 8 , " j o b " : " v i s u a l e f f e c t s p r o d u c e r " , " n a m e " : " a l a i n l a l a n n e " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c d f c 3 a 3 6 8 1 1 5 3 0 0 2 7 2 9 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 0 6 4 1 0 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " l u c a s s a l t o n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 6 2 3 9 2 5 1 4 1 7 a 8 1 0 0 1 e a e " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 2 3 4 2 6 6 , " j o b " : " p o s t p r o d u c t i o n s u p e r v i s o r " , " n a m e " : " j a n a c e t a s h j i a n " } , { " c r e d i t _ i d " : " 5 4 9 5 9 c 8 5 9 2 5 1 4 1 6 e 1 e 0 0 3 e f e " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 2 7 1 9 3 2 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " s t e p h e n r o s e n b a u m " } , { " c r e d i t _ i d " : " 5 5 9 2 a f 2 8 c 3 a 3 6 8 7 7 5 a 0 0 1 0 5 f " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 1 0 0 6 4 , " j o b " : " m a k e u p a r t i s t " , " n a m e " : " f r a n k i e k a r e n a " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a d f c 3 a 3 6 8 1 0 e 3 0 0 2 0 3 b " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 1 3 1 9 8 4 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " l i s a l o v a a s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 b 5 7 9 2 5 1 4 1 6 e 2 b 0 0 4 3 7 1 " , " d e p a r t m e n t " : " v i s u a l e f f e c t s " , " g e n d e r " : 0 , " i d " : 1 3 2 7 0 2 8 , " j o b " : " v i s u a l e f f e c t s s u p e r v i s o r " , " n a m e " : " j o n a t h a n f a w k n e r " } , { " c r e d i t _ i d " : " 5 3 9 c 4 8 a 7 c 3 a 3 6 8 1 0 b 5 0 0 1 f a 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 1 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " r o b e r t b a v i n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 7 1 c 3 a 3 6 8 1 0 d a 0 0 2 1 e 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 6 7 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " a n t h o n y a l m a r a z " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a 8 a c 3 a 3 6 8 1 0 b a 0 0 2 1 e 4 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 0 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " c a r o l y n m . f e n t o n " } , { " c r e d i t _ i d " : " 5 3 9 c 4 a b 6 c 3 a 3 6 8 1 0 d a 0 0 2 1 f 0 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 1 3 3 0 5 7 4 , " j o b " : " c o s t u m e s u p e r v i s o r " , " n a m e " : " b e t h k o e n i g s b e r g " } , { " c r e d i t _ i d " : " 5 4 4 9 1 a b 7 0 e 0 a 2 6 7 4 8 0 0 0 1 b a 2 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 6 1 9 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " s a m p a g e " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 d 9 c 3 a 3 6 8 0 f c 3 0 0 1 8 b d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 3 9 4 4 1 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t e x k a d o n a g a " } , { " c r e d i t _ i d " : " 5 4 4 9 1 c f 5 0 e 0 a 2 6 7 4 8 3 0 0 1 b 0 c " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 3 5 2 4 2 2 , " j o b " : " d i a l o g u e e d i t o r " , " n a m e " : " k i m f o s c a t o " } , { " c r e d i t _ i d " : " 5 4 4 9 1 9 f 4 0 e 0 a 2 6 7 4 8 c 0 0 1 b 0 9 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 0 , " i d " : 1 3 5 2 9 6 2 , " j o b " : " s e t d e s i g n e r " , " n a m e " : " t a m m y s . l e e " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 1 5 c 3 a 3 6 8 0 f f 5 0 0 2 d 7 1 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 0 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " d e n n y c a i r a " } , { " c r e d i t _ i d " : " 5 4 9 5 a 1 2 f 9 2 5 1 4 1 3 0 f c 0 0 2 e 9 4 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 5 7 0 7 1 , " j o b " : " t r a n s p o r t a t i o n c o o r d i n a t o r " , " n a m e " : " j a m e s w a i t k u s " } , { " c r e d i t _ i d " : " 5 4 9 5 9 7 6 f c 3 a 3 6 8 1 1 5 3 0 0 2 6 b 0 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 1 3 6 0 1 0 3 , " j o b " : " s u p e r

In [149]:
new_df['tags'][1]

'c a p t a i n b a r b o s s a , l o n g b e l i e v t o b e d e a d , h a c o m e b a c k t o l i f e a n d i s h e a d t o t h e e d g o f t h e e a r t h w i t h w i l l t u r n e r a n d e l i z a b e t h s w a n n . b u t n o t h i s q u i t a s i t s e e m s . a d v e n t u r f a n t a s i a c t i o n o c e a n d r u g a b u s e x o t i c i s l a n d e a s t i n d i a t r a d i n g c o m p a n i l o v e o f o n e \' s l i f t r a i t o r s h i p w r e c k s t r o n g w o m a n s h i p a l l i a n c c a l y p s o a f t e r l i f f i g h t e r p i r a t s w a s h b u c k l a f t e r c r e d i t s s t i n g j o h n n y d e p p o r l a n d o b l o o m k e i r a k n i g h t l e y [ { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 7 9 " , " d e p a r t m e n t " : " c a m e r a " , " g e n d e r " : 2 , " i d " : 1 2 0 , " j o b " : " d i r e c t o r o f p h o t o g r a p h y " , " n a m e " : " d a r i u s z w o l s k i " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 4 f d " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 2 , " i d " : 1 7 0 4 , " j o b " : " d i r e c t o r " , " n a m e " : " g o r e v e r b i n s k i " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 4 f " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 7 7 0 , " j o b " : " p r o d u c e r " , " n a m e " : " j e r r y b r u c k h e i m e r " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 0 3 " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 1 7 0 5 , " j o b " : " s c r e e n p l a y " , " n a m e " : " t e d e l l i o t t " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 0 9 " , " d e p a r t m e n t " : " w r i t i n g " , " g e n d e r " : 2 , " i d " : 1 7 0 6 , " j o b " : " s c r e e n p l a y " , " n a m e " : " t e r r y r o s s i o " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 7 f " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 0 , " i d " : 1 7 2 1 , " j o b " : " e d i t o r " , " n a m e " : " s t e p h e n e . r i v k i n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 8 5 " , " d e p a r t m e n t " : " e d i t i n g " , " g e n d e r " : 2 , " i d " : 1 7 2 2 , " j o b " : " e d i t o r " , " n a m e " : " c r a i g w o o d " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 7 3 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 2 , " i d " : 9 4 7 , " j o b " : " o r i g i n a l m u s i c c o m p o s e r " , " n a m e " : " h a n s z i m m e r " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 5 5 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 2 4 4 4 , " j o b " : " e x e c u t i v e p r o d u c e r " , " n a m e " : " m i k e s t e n s o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 6 1 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 2 4 4 5 , " j o b " : " p r o d u c e r " , " n a m e " : " e r i c m c l e o d " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 5 b " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 2 , " i d " : 2 4 4 6 , " j o b " : " p r o d u c e r " , " n a m e " : " c h a d o m a n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 6 7 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 0 , " i d " : 2 4 4 7 , " j o b " : " p r o d u c e r " , " n a m e " : " p e t e r k o h n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 6 d " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 0 , " i d " : 2 4 4 8 , " j o b " : " p r o d u c e r " , " n a m e " : " p a t s a n d s t o n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 8 b " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 2 2 1 5 , " j o b " : " c a s t i n g " , " n a m e " : " d e n i s e c h a m i a n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 9 7 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 2 2 6 , " j o b " : " p r o d u c t i o n d e s i g n " , " n a m e " : " r i c k h e i n r i c h s " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 9 d " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 5 5 3 , " j o b " : " a r t d i r e c t i o n " , " n a m e " : " j o h n d e x t e r " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 9 1 " , " d e p a r t m e n t " : " p r o d u c t i o n " , " g e n d e r " : 1 , " i d " : 3 3 1 1 , " j o b " : " c a s t i n g " , " n a m e " : " p r i s c i l l a j o h n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 a 3 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 1 , " i d " : 4 0 3 2 , " j o b " : " s e t d e c o r a t i o n " , " n a m e " : " c h e r y l c a r a s i k " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 a 9 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 0 , " i d " : 4 0 3 3 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " l i z d a n n " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 a f " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 4 0 3 4 , " j o b " : " c o s t u m e d e s i g n " , " n a m e " : " p e n n y r o s e " } , { " c r e d i t _ i d " : " 5 6 4 2 7 c e 8 c 3 a 3 6 8 6 a 5 3 0 0 0 d 8 b " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 2 , " i d " : 5 1 3 2 , " j o b " : " m u s i c s u p e r v i s o r " , " n a m e " : " b o b b a d a m i " } , { " c r e d i t _ i d " : " 5 5 9 9 3 c 1 5 c 3 a 3 6 8 5 5 d b 0 0 2 f 3 3 " , " d e p a r t m e n t " : " a r t " , " g e n d e r " : 2 , " i d " : 1 4 6 4 3 9 , " j o b " : " c o n c e p t u a l d e s i g n " , " n a m e " : " j a m e s w a r d b y r k i t " } , { " c r e d i t _ i d " : " 5 2 f e 4 2 3 2 c 3 a 3 6 8 4 7 f 8 0 0 b 5 b 9 " , " d e p a r t m e n t " : " c o s t u m e & m a k e - u p " , " g e n d e r " : 1 , " i d " : 4 0 6 2 0 4 , " j o b " : " m a k e u p d e p a r t m e n t h e a d " , " n a m e " : " v e n e i l l " } , { " c r e d i t _ i d " : " 5 6 e 4 7 f 7 8 9 2 5 1 4 1 3 2 6 9 0 0 1 7 b d " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 2 , " i d " : 1 2 5 9 5 1 6 , " j o b " : " s t u n t s " , " n a m e " : " j o h n d i x o n " } , { " c r e d i t _ i d " : " 5 7 4 0 b e 6 3 9 2 5 1 4 1 6 5 9 7 0 0 0 8 4 9 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 3 6 7 1 6 , " j o b " : " c g i s u p e r v i s o r " , " n a m e " : " d o t t i e s t a r l i n g " } , { " c r e d i t _ i d " : " 5 6 4 2 7 c 6 3 9 2 5 1 4 1 2 f c 8 0 0 0 d c 1 " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 1 , " i d " : 1 3 4 4 2 7 8 , " j o b " : " s c r i p t s u p e r v i s o r " , " n a m e " : " p a m e l a a l c h " } , { " c r e d i t _ i d " : " 5 7 0 8 3 1 0 1 c 3 a 3 6 8 1 d 3 2 0 0 0 4 e 6 " , " d e p a r t m e n t " : " c r e w " , " g e n d e r " : 0 , " i d " : 1 3 6 8 8 6 7 , " j o b " : " s p e c i a l e f f e c t s c o o r d i n a t o r " , " n a m e " : " a l l e n h a l l " } , { " c r e d i t _ i d " : " 5 6 4 2 7 d 5 e c 3 a 3 6 8 6 a 6 2 0 0 0 d 4 a " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 1 3 6 8 8 8 4 , " j o b " : " m u s i c e d i t o r " , " n a m e " : " m e l i s s a m u i k " } , { " c r e d i t _ i d " : " 5 6 4 2 7 c 7 b 9 2 5 1 4 1 2 f d 4 0 0 0 e 0 7 " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 1 , " i d " : 1 3 9 5 2 9 0 , " j o b " : " s c r i p t s u p e r v i s o r " , " n a m e " : " s h a r r o n r e y n o l d s " } , { " c r e d i t _ i d " : " 5 6 4 2 7 d 2 b c 3 a 3 6 8 6 a 5 3 0 0 0 d 9 b " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 1 3 9 9 3 2 7 , " j o b " : " m u s i c e d i t o r " , " n a m e " : " b a r b a r a m c d e r m o t t " } , { " c r e d i t _ i d " : " 5 6 4 2 7 c b 4 c 3 a 3 6 8 6 a 5 3 0 0 0 d 8 7 " , " d e p a r t m e n t " : " d i r e c t i n g " , " g e n d e r " : 1 , " i d " : 1 4 0 0 7 3 8 , " j o b " : " s c r i p t s u p e r v i s o r " , " n a m e " : " k a r e n g o l d e n " } , { " c r e d i t _ i d " : " 5 6 4 2 7 d 1 6 9 2 5 1 4 1 2 f d 4 0 0 0 e 2 3 " , " d e p a r t m e n t " : " s o u n d " , " g e n d e r " : 0 , " i d " : 1 5 3 4 1 9 7 , " j o b " : " m u s i c e d i t o r " , " n a m e " : " k a t i e g r e a t h o u s e " } ]'

In [150]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [151]:
vectors=cv.fit_transform(new_df['tags']).toarray()

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [ ]:
vectors

In [ ]:
vectors[0]

In [ ]:
len(cv.get_feature_names_out())

In [ ]:
cv.get_feature_names_out()

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vectors)

In [ ]:
#list(enumerate(similarity[0]))

In [ ]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

In [ ]:

similarity[0]

In [ ]:
def recommend(movie):
  movie_index=new_df[new_df['title']==movie].index[0]
  distances=similarity[movie_index]
  movies_list=sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Batman Begins')

In [ ]:

new_df.iloc[1216].title

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [ ]:
new_df['title'].values

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))